# Site settings
title: Naruto Blog
SEOTitle: 火影的博客 | Naruto Blog
header-img: img/post-bg-desk.jpg
email: lanbery@gmail.com
description: "Live for die."
keyword: "Naruto, Naruto Blog, 火影的博客, JNaruto"
url: "https://jnaruto.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jnaruto/jnaruto.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Live for die."
sidebar-avatar: /img/about-naruto.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
#weibo_username:    Naruto
#zhihu_username:    Naruto
github_username:    jnaruto
facebook_username:  Naruto
jianshu_username:   Naruto
twitter_username:   Naruto

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
